title: Project

files:
  sortable: true

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 3/4

  year:
    label: Year
    type:  text
    width: 1/4

  text:
    label: Text
    type:  textarea

  responsibilities:
    label: Responsiblities
    type:  textarea

  github:
    label: GitHub
    type: Url
    
  project_site:
    label: Project Site
    type: Url

  other:
    label: Other Site
    type: Url
